# permissions for end users to view edgepodtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgepodtemplate-viewer-role
rules:
- apiGroups:
  - edge.pete.dev
  resources:
  - edgepodtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.pete.dev
  resources:
  - edgepodtemplates/status
  verbs:
  - get
