# permissions for end users to view edgenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgenode-viewer-role
rules:
- apiGroups:
  - edge.pete.dev
  resources:
  - edgenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.pete.dev
  resources:
  - edgenodes/status
  verbs:
  - get
