# permissions for end users to edit edgepods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgepod-editor-role
rules:
- apiGroups:
  - edge.pete.dev
  resources:
  - edgepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.pete.dev
  resources:
  - edgepods/status
  verbs:
  - get
