
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - edge.pete.dev
  resources:
  - edgedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.pete.dev
  resources:
  - edgedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - edge.pete.dev
  resources:
  - edgedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - edge.pete.dev
  resources:
  - edgenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.pete.dev
  resources:
  - edgenodes/finalizers
  verbs:
  - update
- apiGroups:
  - edge.pete.dev
  resources:
  - edgenodes/status
  verbs:
  - get
  - patch
  - update
