apiVersion: edge.pete.dev/v1alpha1
kind: EdgeDeployment
metadata:
  name: edgedeployment-sample
spec:
  # Add fields here
  edgenodes:
    - edgenode1
    - testedgenode2
    - testedgenode5
  template:
    spec:
      containers:
        - name: nginx
          image: gcr.io/google-containers/echoserver:1.10
          ports:
            - containerPort: 8080
              hostPort: 9091