apiVersion: edge.pete.dev/v1alpha1
kind: EdgeDeployment
metadata:
  name: edgedeployment-sample2
spec:
  # Add fields here
  edgenodes:
    - testedgenode1
    - testedgenode2
    - testedgenode3
  template:
    spec:
      containers:
        - name: nginx
          image: someimage
          ports:
            - containerPort: 8022